# Generated by Django 5.0.7 on 2024-07-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fixed', '-create'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
